Create project_plan.md
waliffcordeiro/Chacao-Investimentos pull request #17
Opened 2020-10-20 02:42 UTC by PedroAugustoRamalhoDuarte

2020-10-20 02:51 UTC, emanuks approved these changes

2020-10-20 15:37 UTC, waliffcordeiro requested changes

2020-10-20 15:37 UTC, waliffcordeiro commented on Artefatos/project_plan.md
> +O projeto será realizado pelos desenvolvedores Pedro Augusto, Emanuel e Waliff. E será divido em 3 funções pricipais Documentação/Artefatos que serão desenvolvidos por todos os membros, Back-end que
consertar a palavra 'comunicação'

2020-10-20 15:37 UTC, waliffcordeiro commented on Artefatos/project_plan.md
> +A métodologia utilizada será o Scrum, com algumas adaptações para o período de pandemia. O daily meeting será realizado a cada 2 dias por meio da plataforma WhatsApps; O Sprint planning será realizad
"todas as segundas-feiras"
E ficaria legal colocar um . e ao invés de ambas . Todas cerimônias ...

2020-10-20 15:37 UTC, waliffcordeiro commented on Artefatos/project_plan.md
> +- Planejamento incial das sprints é importante.
"inicial"

2020-10-20 15:37 UTC, waliffcordeiro commented on Artefatos/project_plan.md
> +- É fundamental aplicar reuniões recorrenetes para o bom alinhamento do projeto e progresso.
"recorrentes"

2020-10-20 15:49 UTC, waliffcordeiro requested changes

2020-10-20 15:49 UTC, waliffcordeiro commented on Artefatos/project_plan.md
> +O projeto será realizado pelos desenvolvedores Pedro Augusto, Emanuel e Waliff. E será divido em 3 funções pricipais Documentação/Artefatos que serão desenvolvidos por todos os membros, Back-end que
"principais"

2020-10-20 15:49 UTC, waliffcordeiro commented on Artefatos/project_plan.md
> +O projeto será realizado pelos desenvolvedores Pedro Augusto, Emanuel e Waliff. E será divido em 3 funções pricipais Documentação/Artefatos que serão desenvolvidos por todos os membros, Back-end que
"whatsapp"

2020-10-20 15:49 UTC, waliffcordeiro commented on Artefatos/project_plan.md
> +Todo final de interação o site em produção será atualizado no heroku por meio do github actions, quando a pull request realizada for aprovado e mergida com a master. E a documentação será disponibili
"iteração"

2020-10-21 16:20 UTC, waliffcordeiro requested changes

2020-10-21 16:20 UTC, waliffcordeiro commented on Artefatos/project_plan.md
> +### Project milestones and objectives
Recalcular a target velocity

2020-10-21 16:20 UTC, waliffcordeiro commented on Artefatos/project_plan.md
> +### Lessons learned
É legal falar que estamos o sistema de review para aprovações dos PRs

2020-10-22 18:48 UTC, PedroAugustoRamalhoDuarte commented on Artefatos/project_plan.md
> +### Lessons learned
done

2020-10-22 19:08 UTC, waliffcordeiro approved these changes

2020-10-22 19:16 UTC, merged