Iteration Plan
waliffcordeiro/Chacao-Investimentos pull request #18
Opened 2020-10-23 04:06 UTC by waliffcordeiro

#3 

Tive que colocar a imagem no mesmo diretório dos artefatos pois não consegui incluir a imagem no md a partir de outro diretório.

Essa issue conta com que o projeto já esteja concluído, no última sprint compensa dar uma olhada pois coloquei o que acredito que acontecerá, mas podemos dar uma revisada.

2020-10-23 13:42 UTC, PedroAugustoRamalhoDuarte requested changes

2020-10-23 13:42 UTC, PedroAugustoRamalhoDuarte commented on Artefatos/iteration_plan.md
> +Neste documento você encontrará informações sobre a organização do projeto com foco nas iterações. O projeto está sendo desenvolvido seguindo a metodologia ágil Scrum. O projeto está sendo versionado
Talvez colocar o texto para especificar melhor: "providas por ele para organizarmos a Sprint como milestones ou algo do tipo"

2020-10-23 13:42 UTC, PedroAugustoRamalhoDuarte commented on Artefatos/iteration_plan.md
> +Fora essas datas temos o Daily Scrum que é feito via WhatsApp para uma rápida atualização do trabalho do time no dia em questão.
Isso aqui ta um pouco desconexo com o plano, lá está falando que não fazemos o Daily Scrum todo dia e fazemos uma dinamica parecida que seria na quarta, o que acho mais plausível

2020-10-23 13:42 UTC, PedroAugustoRamalhoDuarte commented on Artefatos/iteration_plan.md
> +- Passar em 95% dos testes em nível de sistema.
Porque 95%? acho que pode ser 100% suaves

2020-10-23 13:42 UTC, PedroAugustoRamalhoDuarte commented on Artefatos/iteration_plan.md
> +A parte da implementação contou com pouco tempo mas já era previsto no planejamento pois não consistia no foco do projeto desenvolvido, apesar disso o resultado foi satisfatorio.
**satisfatório**

2020-10-23 13:59 UTC, PedroAugustoRamalhoDuarte approved these changes
Excelente!!

2020-10-25 03:19 UTC, emanuks commented on Artefatos/iteration_plan.md
> +A Start Date da Sprint é o Sprint Planing, feito com uma revisão do Backlog Project, fazendo alguma atualização caso necessário.
Corrigir a palavra 'Planning'.

2020-10-25 03:20 UTC, emanuks requested changes

2020-10-25 03:20 UTC, emanuks commented on Artefatos/iteration_plan.md
> +A Start Date da Sprint é o Sprint Planing, feito com uma revisão do Backlog Project, fazendo alguma atualização caso necessário.
Corrigir a palavra 'Planning'.

2020-10-26 02:03 UTC, emanuks approved these changes

2020-10-26 02:03 UTC, emanuks commented
Boa!

2020-10-26 10:21 UTC, merged