Vision document
waliffcordeiro/Chacao-Investimentos pull request #19
Opened 2020-10-24 16:13 UTC by PedroAugustoRamalhoDuarte

2020-10-24 16:33 UTC, waliffcordeiro requested changes

2020-10-24 16:33 UTC, waliffcordeiro commented on Artefatos/vision.md
> +Neste documento você encontrará informações sobre a visão do produto a ser produzido, com foco no posicionamento de mercado, stakeholders, modelo de negócio e detalhes de produto.
'produto a ser produzido'  ficou meio estranho, talvez só 'visão do produto' ou 'visão geral do produto'

2020-10-24 16:33 UTC, waliffcordeiro commented on Artefatos/vision.md
> +| Nos quais                      | gostariam de fazer seu patrimonio crescer ou conseguir uma indepêndencia financeira com baixo riscos        |
**patrimônio**

2020-10-24 16:33 UTC, waliffcordeiro commented on Artefatos/vision.md
> +| Nos quais                      | gostariam de fazer seu patrimonio crescer ou conseguir uma indepêndencia financeira com baixo riscos        |
**independência**

2020-10-24 16:33 UTC, waliffcordeiro commented on Artefatos/vision.md
> +| A (Chacão Investimento)        | é uma corretora de investimentos                                                                            |
uma corretora virtual, talvez?

2020-10-24 16:33 UTC, waliffcordeiro commented on Artefatos/vision.md
> +| Ao contrário                   | das concorrentes que só enfocam nos clientes com mais renda e com altas taxas de 1% sobre o valor investido |
com maior renda

2020-10-24 16:33 UTC, waliffcordeiro commented on Artefatos/vision.md
> +| Dreams Bank          | Banco internacional que financia startups pelo mundo       |  - Financiar a equipe de software - Manter os custos de hospedagem e manuntenção  |
Acho que nas responsibilities não precisa deixar o - ( tracinho, visto que é uma tabela )

2020-10-24 16:33 UTC, waliffcordeiro commented on Artefatos/vision.md
> +| Switch Marketing          | Empresa referência em marketing digital      |  - Marketing  |
responsibilities do marketing : conhecer o consumidor, estudar o mercado e promover a imagem da instituição (ou empresa?)

2020-10-24 16:33 UTC, waliffcordeiro commented on Artefatos/vision.md
> +Para finalizar o MVP serão necessários 3 desenvolvedores, esses mesmos serão responsáveis pela manunteção da plataforma, e para futuras features ou atualizações serão contratados novos desenvolvedore
**Switch Marketing**

2020-10-24 16:33 UTC, waliffcordeiro commented on Artefatos/vision.md
> +Será disponibilizado um contato por e-mail, no qual uma pessoa com ajuda de um robô de atendimento ficará responsável por resolver dúvidas dos clientes em horário comercial. Há pretensões de aumento
**consumidor**

2020-10-24 16:33 UTC, waliffcordeiro commented on Artefatos/vision.md
> +| Need                           | Priority | Features                                                                                 | Planned Realease       |
Será que seria interessante incluir uma dashboard? Explicitar que terá um painel com gráficos para melhor visualização

2020-10-24 16:33 UTC, waliffcordeiro commented on Artefatos/vision.md
> +Nossa aplicação principal será um website que rodará em qualquer dispositivo conectado a internet. A interface será responsiva, com o design otimizado tanto para dispositivos mobiles como computadore
**conectado à internet** e acho que mobiles ficaria no singular, não tenho certeza 'dispositivos mobile'

2020-10-24 17:01 UTC, waliffcordeiro requested changes

2020-10-24 17:01 UTC, waliffcordeiro commented on Artefatos/vision.md
> +Para finalizar o MVP serão necessários 3 desenvolvedores, esses mesmos serão responsáveis pela manunteção da plataforma, e para futuras features ou atualizações serão contratados novos desenvolvedore
**Switch Marketing**

2020-10-25 03:23 UTC, emanuks approved these changes

2020-10-25 03:38 UTC, waliffcordeiro commented
Parabéns pelo Artefato gerado, ficou muito bom !

2020-10-28 22:21 UTC, waliffcordeiro approved these changes

2020-10-29 15:26 UTC, merged