Project Defined Process
waliffcordeiro/Chacao-Investimentos pull request #20
Opened 2020-10-24 17:00 UTC by waliffcordeiro

Desenvolvimento do artefato Project Defined Process

2020-10-25 03:26 UTC, emanuks requested changes

2020-10-25 03:26 UTC, emanuks commented on Artefatos/project_defined_process.md
> +Para transmitirmos a seriedade, confiança e segurança da Chacão investimentos a corretora de valores na CVM (Comissão de Valores Mobiliários, Lei 6.385/76) e ficará sob supervisão no site do Banco Ce
Trocar 'Chacão investimentos' por 'Chacão Investimentos'.

2020-10-25 21:54 UTC, PedroAugustoRamalhoDuarte approved these changes
Excelente!!

2020-10-26 02:02 UTC, emanuks approved these changes

2020-10-26 02:03 UTC, emanuks commented
Boa!

2020-10-26 10:20 UTC, merged