Glossary
waliffcordeiro/Chacao-Investimentos pull request #22
Opened 2020-10-25 01:30 UTC by emanuks

Closes #5 
Desenvolvimento do artefato Glossary

2020-10-25 03:33 UTC, waliffcordeiro requested changes

2020-10-25 03:33 UTC, waliffcordeiro commented on Artefatos/glossary.md
> +Neste documento você encontrará definição de termos importantes usados no projeto. Estes termos são a base para a colaboração eficaz com os Stakeholders e outros membros da equipe.
Minha sugestão de frase:
"Neste documento você encontrará a definição de termos importantes usados no projeto, estes termos são a base para uma colaboração eficaz com os Stakeholders e outros membros da equipe." (talvez scrum team ao invés de equipe, não sei)

2020-10-25 03:33 UTC, waliffcordeiro commented on Artefatos/glossary.md
> +| Artefato | Documento criado durante desenvolvimento de software. |
durante **o** desenvolvimento

2020-10-25 03:33 UTC, waliffcordeiro commented on Artefatos/glossary.md
> +| Resultado | Informação devolvida ao cliente. |
Fiquei em dúvida nessa, o resultado se limita a informação? Não pode ser o produto também, por exemplo?

2020-10-25 03:33 UTC, waliffcordeiro commented on Artefatos/glossary.md
> +| Scrum | Framework de gerenciamento de projeto iterativo usado no desenvolvimento ágil, no qual uma equipe concorda com os itens de desenvolvimento de um backlog de requisitos e os produz em um curt
"... e os produz, geralmente, em um curto período de algumas semanas"

2020-10-25 03:39 UTC, waliffcordeiro commented
Gostei bastante do Glossário, parabéns !

2020-10-26 01:43 UTC, emanuks commented on Artefatos/glossary.md
> +| Resultado | Informação devolvida ao cliente. |
Foi a definição que encontrei no sevocab

2020-10-26 13:24 UTC, PedroAugustoRamalhoDuarte approved these changes
Boa!!

2020-10-30 23:55 UTC, waliffcordeiro requested changes

2020-10-30 23:55 UTC, waliffcordeiro commented on Artefatos/glossary.md
> +| Backlog | Lista de requisitos de produtos e entregas que não fazem parte do trabalho atual, a serem priorizados e concluídos. |
Talvez fique melhor: Lista de requisitos de produtos e entregas a serem priorizados e concluídos mas que não fazem parte do trabalho atual,

2020-11-01 18:42 UTC, waliffcordeiro approved these changes

2020-11-01 18:42 UTC, merged