Tools
waliffcordeiro/Chacao-Investimentos pull request #23
Opened 2020-10-25 03:02 UTC by emanuks

Closes #4 
Desenvolvimento do artefato Lista de Ferramentas (Tools)

2020-10-25 03:37 UTC, waliffcordeiro requested changes

2020-10-25 03:37 UTC, waliffcordeiro commented on Artefatos/tools.md
> +| Discord | Discord é uma plataforma de chat em grupo de uso geral para todos os tipos de comunidades. |
Acho que é legal citar a facilidade de chamada de voz ou videochamada, e relacionar às nossas meetings semanais que chamamos de daily scrum mas é só uma por semana

2020-10-25 03:37 UTC, waliffcordeiro commented on Artefatos/tools.md
> +| Rails | Rails é um framework de desenvolvimento de aplicações web que inclui tudo o que é necessário para criar aplicações web baseados em banco de dados de acordo com o padrão MVC. |
Na descrição talvez seja interessante falar que é vinculado à linguagem Ruby

2020-10-25 03:37 UTC, waliffcordeiro commented on Artefatos/tools.md
> +| RubyMine | RubyMine é um ambiente de desenvolvimento integrado (IDE) para Ruby e Rails. |
Ruby on Rails ao invés de Ruby e Rails?

2020-10-26 01:56 UTC, emanuks commented on Artefatos/tools.md
> +| RubyMine | RubyMine é um ambiente de desenvolvimento integrado (IDE) para Ruby e Rails. |
Na real são os dois, mas vou colocar soh o ruby on rails então

2020-10-29 15:36 UTC, waliffcordeiro approved these changes

2020-10-29 19:56 UTC, PedroAugustoRamalhoDuarte approved these changes
Excelente!

2020-10-30 17:58 UTC, merged