Architecture notebook
waliffcordeiro/Chacao-Investimentos pull request #24
Opened 2020-11-01 17:36 UTC by PedroAugustoRamalhoDuarte

closes #10

2020-11-02 17:42 UTC, waliffcordeiro requested changes

2020-11-02 17:42 UTC, waliffcordeiro commented on Artefatos/architecure_notebook.md
> +Este documento fornece uma visão geral da arquitetura abrangente do sistema, usando uma série de views diferentes para descrever diferentes aspectos do sistema. O objetivo é capturar e transmitir as
"diferentes para descrever diferentes" acho que poderia ser "diferentes para descrever diversos aspectos"

2020-11-02 17:42 UTC, waliffcordeiro commented on Artefatos/architecure_notebook.md
> +sistema de gerenciamento de catálogo e o sistema de gerência de aplicações. O Sistema de cadastro de clientes possuirá duas model, uma chamada User e outra chamada Role para armazenar as
"duas **models**"

2020-11-02 17:42 UTC, waliffcordeiro commented on Artefatos/architecure_notebook.md
> +funções do usuário dentro do sistema que no caso serão duas: Customer e Admin, e duas controller: UsersController que será responsável pelo CRUD do usuário e a SessionsController que
"duas **controllers**"

2020-11-02 17:42 UTC, waliffcordeiro commented on Artefatos/architecure_notebook.md
> +A aplicação é formada por três subsistemas principais, sendo que o o susbistema de usuários tem a responsabilidade de gerenciamento de usuários e sessions, o sistema de gerenciamento de catálogo
"susbistema" "subsistema"

2020-11-02 17:42 UTC, waliffcordeiro commented on Artefatos/architecure_notebook.md
> +tem a responsabilidade de gerenciar a disponibilidade de investimentos na plataforma e o sistema de gerenciamento de aplicações, depende dos dois outros sistemas para gerenciar os invesitimentos dos
"invesitimentos"

2020-11-02 21:21 UTC, emanuks approved these changes

2020-11-03 00:01 UTC, PedroAugustoRamalhoDuarte commented
@waliffcordeiro finalizei as alterações, só falta tua aprovação

2020-11-03 14:09 UTC, waliffcordeiro approved these changes

2020-11-03 14:22 UTC, merged