Use case model
waliffcordeiro/Chacao-Investimentos pull request #25
Opened 2020-11-03 22:51 UTC by waliffcordeiro

Modelo de caso de uso

2020-11-04 01:31 UTC, PedroAugustoRamalhoDuarte requested changes

2020-11-04 01:31 UTC, PedroAugustoRamalhoDuarte commented on Artefatos/use_case_model.md
> +O artefato do modelo de casos de uso pode ser customizado para atender as necessidades da equipe.
Achei o parágrafo um pouco sem fluidez, talvez colocar uma vírgula no lugar do pontos, porque ainda é o mesmo assunto  ", é a base", serve também como um guia ... e pode ser customizado para atender a necessidades da equipe

2020-11-04 14:46 UTC, PedroAugustoRamalhoDuarte approved these changes

2020-11-04 14:46 UTC, PedroAugustoRamalhoDuarte commented
@waliffcordeiro boa goiano!!

2020-11-06 02:01 UTC, emanuks approved these changes
Ótimo!

2020-11-06 11:53 UTC, merged