User interface design
waliffcordeiro/Chacao-Investimentos pull request #26
Opened 2020-11-07 05:58 UTC by emanuks

Closes #11

2020-11-07 12:56 UTC, PedroAugustoRamalhoDuarte approved these changes
Fino do fino

2020-11-10 10:00 UTC, waliffcordeiro requested changes
Acrescentei o artigo aos sujeitos cliente e administrador

2020-11-10 10:00 UTC, waliffcordeiro commented on Artefatos/user_interface_design.md
> +Diagrama de interfaces disponíveis para administrador da aplicação.
```suggestion
Diagrama de interfaces disponíveis para o administrador da aplicação.
```

2020-11-10 10:00 UTC, waliffcordeiro commented on Artefatos/user_interface_design.md
> +Diagrama de interfaces disponíveis para cliente da aplicação.
```suggestion
Diagrama de interfaces disponíveis para o cliente da aplicação.
```

2020-11-11 15:50 UTC, waliffcordeiro approved these changes
Fino!

2020-11-11 21:21 UTC, merged