Infrastructure
waliffcordeiro/Chacao-Investimentos pull request #27
Opened 2020-11-07 13:59 UTC by PedroAugustoRamalhoDuarte

closes #16

2020-11-08 20:48 UTC, emanuks requested changes

2020-11-08 20:48 UTC, emanuks commented on Artefatos/infrastructure.md
> + mergidas posteriormente, quando validadas por meio de testes automatizado utilizando RSPEC, por meio da equipe de projeto com testes manuais e
A palavra mergidas está repetida

2020-11-08 20:48 UTC, emanuks commented on Artefatos/infrastructure.md
> + para o desenvolvimento e caso sejam validadas o processo segue para parte do merge da develop com a main, depois é criada a realease no github com o changelog e
Corrigir a palavra release

2020-11-08 20:48 UTC, emanuks commented on Artefatos/infrastructure.md
> + ![diagrama](diagrama_infrastructure.png)
Corrigir a palavra release

2020-11-10 09:58 UTC, waliffcordeiro approved these changes

2020-11-11 12:37 UTC, emanuks approved these changes

2020-11-11 12:38 UTC, emanuks commented
Boa!

2020-11-11 18:18 UTC, merged