Use cases
waliffcordeiro/Chacao-Investimentos pull request #28
Opened 2020-11-10 12:32 UTC by waliffcordeiro

closes #9

2020-11-10 20:52 UTC, PedroAugustoRamalhoDuarte requested changes

2020-11-10 20:52 UTC, PedroAugustoRamalhoDuarte commented on Artefatos/use_cases.md
> +____
Tem deleção de usuários?

2020-11-10 20:52 UTC, PedroAugustoRamalhoDuarte commented on Artefatos/use_cases.md
> +- Acesso à plataforma
```suggestion
- Acesso à plataforma e redirecionamento para página principal
```

2020-11-10 20:52 UTC, PedroAugustoRamalhoDuarte commented on Artefatos/use_cases.md
> +- Neste caso, o administrador sempre irá salvar o novo produto ou editar os dados para tentar salvar novamente
```suggestion
- O caso de uso começa quando um novo produto precisa ser inserido na plataforma
- O admistrador preenche o formulário de criação de produto
- Verifica se todos os dados obrigatórios estão preenchidos
- Verifica se todos os dados preenchidos estão corretos de acordo com o seu tipo e restrições
- Neste caso, o administrador sempre irá salvar o novo produto ou editar os dados para tentar salvar novamente
```

2020-11-10 20:52 UTC, PedroAugustoRamalhoDuarte commented on Artefatos/use_cases.md
> +- O servidor precisa ter capacidade de armazenamento para a alteração dos dados
Edição de produto creio que não teremos

2020-11-10 20:52 UTC, PedroAugustoRamalhoDuarte commented on Artefatos/use_cases.md
> +1. **Alternative Flows**
```suggestion
5. **Alternative Flows**
```

2020-11-10 21:31 UTC, PedroAugustoRamalhoDuarte approved these changes
Fino!!

2020-11-11 12:43 UTC, emanuks requested changes

2020-11-11 12:43 UTC, emanuks commented on Artefatos/use_cases.md
> +5. **Alternative Flows**
Não será possível editar CPF, portanto não existem alternative flows relacionados ao CPF na edição de usuário.

2020-11-11 21:22 UTC, emanuks approved these changes
Boa!!!

2020-11-11 21:26 UTC, PedroAugustoRamalhoDuarte commented on Artefatos/use_cases.md
> +5. **Alternative Flows**
Preciso comentário

2020-11-12 12:12 UTC, merged