Adding system wide requirements
waliffcordeiro/Chacao-Investimentos pull request #40
Opened 2020-11-22 04:12 UTC by emanuks

Closes #7

2020-11-22 14:06 UTC, waliffcordeiro requested changes

2020-11-22 14:06 UTC, waliffcordeiro commented on Artefatos/system_wide_requirements.md
> +- Segurança: Os dados de usuário e conta bancária não deverão ser acessíveis por outro usuário que não for o usuário vinculado às informações ou administrador.
Ressaltar que a senha não é acessível nem mesmo pelo administrador?

Algo como 'Através do sistema de login a senha é armazenada com um hash e fica inacessível', aí você vê como fica bom, caso queira acrescentar

2020-11-22 14:06 UTC, waliffcordeiro commented on Artefatos/system_wide_requirements.md
> +- Facilidade de aprendizado: O sistema deve ser intuitivo de maneira a facilitar a utilização do sistema a qualquer tipo de usuário.
```suggestion
- Facilidade de aprendizado: O sistema deve ser intuitivo de maneira a facilitar a utilização para qualquer tipo de usuário.
```

2020-11-22 14:06 UTC, waliffcordeiro commented on Artefatos/system_wide_requirements.md
> +- Capacidade de Recuperação: O sistema não deve ficar fora do ar por mais de 7h por semana.
```suggestion
- Capacidade de Recuperação: O sistema não deve ficar fora do ar por mais de 7 horas por semana.
```

2020-11-22 14:06 UTC, waliffcordeiro commented on Artefatos/system_wide_requirements.md
> +- Adaptabilidade: O sistema deve se adaptar e incorporar novos tipos de aplicação financeira.
```suggestion
- Adaptabilidade: O sistema deve se adaptar e incorporar novos tipos de aplicações financeiras.
```

2020-11-22 14:06 UTC, waliffcordeiro commented on Artefatos/system_wide_requirements.md
> +- Linguagem de Programação: O sistema deve ser implementado em Ruby on Rails.
talvez "Na linguagem Ruby através do framework Ruby on Rails"

2020-11-24 12:51 UTC, PedroAugustoRamalhoDuarte approved these changes
Boaa!!

2020-11-24 13:14 UTC, waliffcordeiro approved these changes
Boa !

2020-11-24 13:41 UTC, merged